### ISSUE TITLE
Replace truffle with buidler

### ISSUE THREAD

**Issue by paxthemax** [commons-stack/tech-token#16]
I would propose we replace truffle with buidler, as it should be mature enough to support the project.

It has many advantages:
- `console.log` in contracts for debugging
- Typescript support in tests
- Typechain support for contract stub code generation

The only downside is that migrations are not directly compatible (to my knowledge) - but there is a way to create a workaround - a manual script to perform migrations.

**Comment by sponnet** [comment]
@DaLN what do you think ?
