### ISSUE TITLE
Registry needs to be converted to a Max% of total supply instead of a set # of CSTK tokens

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/tech-token#34]
After a review of the token economics of the CSTK token with Z, we got mostly gold stars, except for 1 thing:

The registry, if denominated in CSTK tokens, can be an impediment for big contributors to contribute more... it becomes a sort of race to get to the top and then stop... like the game is over, final level reached and accomplished...

so there Z wanted a sort of deflationary approach, where the #of cstk tokens you have starts to dissolve if you dont contribute.... but that seemed sort of complicated to implement to me, and no one wants to see their trust amount go down

so we settled on a inflationary/dilution approach... its not perfect, but I think a good compromise... but to pull it off, we would want to have the registry be limiting people on % of total supply instead of a flat # of CSTK tokens

The idea would be that the registry would track % of total supply allowed... this % would not have to add up to 100%... in fact... the entire registry might add up to 10,000% and thats ok... 

But when the DApp checks to see how much someone should buy, there should be a function that converts the % allowed into a discrete # of CSTK tokens and that is the maxTrust :-D

**Comment by GriffGreen** [comment]
Oh and if people are above their % it's ok.... its not an error

**Comment by DaLN** [comment]
https://github.com/commons-stack/tech-token/commit/66d51f3450e0fcb80b59b66fde647618c25a7e12

**Comment by GriffGreen** [comment]
done here, the current stucture on develop looks good: https://github.com/commons-stack/tech-token/blob/develop/contracts/registry/Registry.sol
