### ISSUE TITLE
Tech Token has a whitelist

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/tech-token#5]
This whitelist allows one account (Coach B) to add people to the whitelist, no one can receive tech tokens without being added to the whitelist. 

There will be a KYC process that is controlled by the Commons Stack Association and Mt. Pelerin. Everyone must go thru this process before they can get tokens.

**Comment by sponnet** [comment]
the whitelist shouls also have a limit on tokens that any account can receive. If this number is 0 - the account has no limit. If it has a number > 0 - this means that this address can only receive up to this amount of tech tokens. This should be part of the controller.
