### ISSUE TITLE
tech token has a proxy buy

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/tech-token#7]
we whitelist the address that people send ETH from and then let them choose a different address to send their tokens too... (tho default should be the  sending address i think... maybe like a check box or something...)

**Comment by sponnet** [comment]
If I am buying tokens on your behalf and use this function to send the tokens to your address, should only I (the sender) be whitelisted - or the recipient of the token ? (or both?)

**Comment by lorelei1** [comment]
@GriffGreen did you answer this anywhere to @sponnet ? Does he need this info before he can create the token contract?

**Comment by sponnet** [comment]
Currently you can specify the target address where the tokens are minted to.

```
   function contribute(uint256 _contributionAmount,address _recepient) public onlyWhitelisted {

```
